/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
int fibonacci(int n ) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
typedef unsigned long size_t;
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__nonnull__(1), __leaf__)) strlen)(char const   *__s )  __attribute__((__pure__)) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int scanf(char const   *format  , ...) ;
extern int raise(int sig ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
void array_processor(int *arr , int size ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void signal(int sig , void *func ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
void menu_handler(int choice ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
    long tv_sec ;
    long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
                                                                                     extern long time(long *tloc ) ;
                                                                                     extern int read(int filedes , void *buf , unsigned int nbyte ) ;
                                                                                     extern int rand() ;
                                                                                     extern int strcmp(char const   *a , char const   *b ) ;
                                                                                     extern void *fopen(char const   *filename , char const   *mode ) ;
                                                                                     extern double sqrt(double x ) ;
                                                                                     int grade_calculator(int score ) ;
                                                                                     extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
                                                                                     extern long strtol(char const   *str , char const   *endptr , int base ) ;
                                                                                     extern void *malloc(unsigned int size ) ;
                                                                                     extern int nanosleep(int *rqtp , int *rmtp ) ;
                                                                                     extern int pthread_mutex_unlock(int *mutex ) ;
                                                                                     extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
                                                                                     extern int atoi(char const   *s ) ;
                                                                                     int string_analyzer(char const   *str ) ;
                                                                                     extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
                                                                                     extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
                                                                                     void megaInit(void) ;
                                                                                     void menu_handler(int choice )
                                                                                     {


                                                                                         {
                                                                                             switch (choice) {
                                                                                                 case 1:
                                                                                                     printf((char const   */* __restrict  */)"Opening file...\n");
                                                                                                     break;
                                                                                                 case 2:
                                                                                                     printf((char const   */* __restrict  */)"Saving file...\n");
                                                                                                     break;
                                                                                                 case 3:
                                                                                                     printf((char const   */* __restrict  */)"Printing document...\n");
                                                                                                     break;
                                                                                                 case 4:
                                                                                                     printf((char const   */* __restrict  */)"Exiting program...\n");
                                                                                                     exit(0);
                                                                                                 default:
                                                                                                     printf((char const   */* __restrict  */)"Invalid choice. Please try again.\n");
                                                                                                     break;
                                                                                             }
                                                                                             return;
                                                                                         }
                                                                                     }
                                                                                     void megaInit(void)
                                                                                     {


                                                                                         {

                                                                                         }
                                                                                     }
                                                                                     int grade_calculator(int score )
                                                                                     {
                                                                                         char grade ;
                                                                                         unsigned long _1_grade_calculator_next ;

                                                                                         {
                                                                                             {
                                                                                                 _1_grade_calculator_next = 8UL;
                                                                                             }
                                                                                             while (1) {
                                                                                                 switch (_1_grade_calculator_next) {
                                                                                                     case 4: ;
                                                                                                     if (score >= 70) {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 7UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 1UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 8: ;
                                                                                                     if (score >= 90) {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 0UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 5UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 1: ;
                                                                                                     if (score >= 60) {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 3UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 6UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 3:
                                                                                                         grade = (char )'D';
                                                                                                         printf((char const   */* __restrict  */)"Below average.\n");
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 9UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 9: ;
                                                                                                     return ((int )grade);
                                                                                                     break;
                                                                                                     case 6:
                                                                                                         grade = (char )'F';
                                                                                                         printf((char const   */* __restrict  */)"Failing grade.\n");
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 9UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 5: ;
                                                                                                     if (score >= 80) {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 2UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 4UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 0:
                                                                                                         grade = (char )'A';
                                                                                                         printf((char const   */* __restrict  */)"Excellent work!\n");
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 9UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 7:
                                                                                                         grade = (char )'C';
                                                                                                         printf((char const   */* __restrict  */)"Average performance.\n");
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 9UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 2:
                                                                                                         grade = (char )'B';
                                                                                                         printf((char const   */* __restrict  */)"Good job!\n");
                                                                                                         {
                                                                                                             _1_grade_calculator_next = 9UL;
                                                                                                         }
                                                                                                         break;
                                                                                                 }
                                                                                             }
                                                                                         }
                                                                                     }
                                                                                     int fibonacci(int n )
                                                                                     {
                                                                                         int tmp ;
                                                                                         int tmp___0 ;

                                                                                         {
                                                                                             if (n <= 1) {
                                                                                                 return (n);
                                                                                             }
                                                                                             tmp = fibonacci(n - 1);
                                                                                             tmp___0 = fibonacci(n - 2);
                                                                                             return (tmp + tmp___0);
                                                                                         }
                                                                                     }
                                                                                     void array_processor(int *arr , int size )
                                                                                     {
                                                                                         int sum ;
                                                                                         int max ;
                                                                                         int min ;
                                                                                         int i ;
                                                                                         unsigned long _1_array_processor_next ;

                                                                                         {
                                                                                             {
                                                                                                 _1_array_processor_next = 12UL;
                                                                                             }
                                                                                             while (1) {
                                                                                                 switch (_1_array_processor_next) {
                                                                                                     case 4: ;
                                                                                                     if (*(arr + i) > max) {
                                                                                                         {
                                                                                                             _1_array_processor_next = 8UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_array_processor_next = 6UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 14:
                                                                                                         printf((char const   */* __restrict  */)"Odd number found: %d\n", *(arr + i));
                                                                                                         {
                                                                                                             _1_array_processor_next = 11UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 12:
                                                                                                         sum = 0;
                                                                                                         max = *(arr + 0);
                                                                                                         min = *(arr + 0);
                                                                                                         i = 0;
                                                                                                         {
                                                                                                             _1_array_processor_next = 13UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 8:
                                                                                                         max = *(arr + i);
                                                                                                         {
                                                                                                             _1_array_processor_next = 6UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 1:
                                                                                                         printf((char const   */* __restrict  */)"Even number found: %d\n", *(arr + i));
                                                                                                         {
                                                                                                             _1_array_processor_next = 11UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 3: ;
                                                                                                     if (*(arr + i) % 2 == 0) {
                                                                                                         {
                                                                                                             _1_array_processor_next = 1UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_array_processor_next = 14UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 11:
                                                                                                         i ++;
                                                                                                         {
                                                                                                             _1_array_processor_next = 13UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 13: ;
                                                                                                     if (i < size) {
                                                                                                         {
                                                                                                             _1_array_processor_next = 0UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_array_processor_next = 2UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 6: ;
                                                                                                     if (*(arr + i) < min) {
                                                                                                         {
                                                                                                             _1_array_processor_next = 5UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_array_processor_next = 3UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 5:
                                                                                                         min = *(arr + i);
                                                                                                         {
                                                                                                             _1_array_processor_next = 3UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 10: ;
                                                                                                     return;
                                                                                                     break;
                                                                                                     case 0:
                                                                                                         sum += *(arr + i);
                                                                                                         {
                                                                                                             _1_array_processor_next = 4UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 2:
                                                                                                         printf((char const   */* __restrict  */)"Sum: %d, Max: %d, Min: %d\n", sum, max,
                                                                                                                min);
                                                                                                         {
                                                                                                             _1_array_processor_next = 10UL;
                                                                                                         }
                                                                                                         break;
                                                                                                 }
                                                                                             }
                                                                                         }
                                                                                     }
                                                                                     int string_analyzer(char const   *str )
                                                                                     {
                                                                                         int length ;
                                                                                         size_t tmp ;
                                                                                         int vowels ;
                                                                                         int consonants ;
                                                                                         int digits ;
                                                                                         int i ;
                                                                                         char c ;

                                                                                         {
                                                                                             tmp = strlen(str);
                                                                                             length = (int )tmp;
                                                                                             vowels = 0;
                                                                                             consonants = 0;
                                                                                             digits = 0;
                                                                                             i = 0;
                                                                                             while (i < length) {
                                                                                                 c = (char )*(str + i);
                                                                                                 if ((int )c >= 48) {
                                                                                                     if ((int )c <= 57) {
                                                                                                         digits ++;
                                                                                                     } else {
                                                                                                         goto _L___1;
                                                                                                     }
                                                                                                 } else
                                                                                                     _L___1: /* CIL Label */
                                                                                                     if ((int )c >= 97) {
                                                                                                         if ((int )c <= 122) {
                                                                                                             goto _L;
                                                                                                         } else {
                                                                                                             goto _L___0;
                                                                                                         }
                                                                                                     } else
                                                                                                         _L___0: /* CIL Label */
                                                                                                         if ((int )c >= 65) {
                                                                                                             if ((int )c <= 90) {
                                                                                                                 _L: /* CIL Label */
                                                                                                                 if ((int )c == 97) {
                                                                                                                     vowels ++;
                                                                                                                 } else
                                                                                                                     if ((int )c == 101) {
                                                                                                                         vowels ++;
                                                                                                                     } else
                                                                                                                         if ((int )c == 105) {
                                                                                                                             vowels ++;
                                                                                                                         } else
                                                                                                                             if ((int )c == 111) {
                                                                                                                                 vowels ++;
                                                                                                                             } else
                                                                                                                                 if ((int )c == 117) {
                                                                                                                                     vowels ++;
                                                                                                                                 } else
                                                                                                                                     if ((int )c == 65) {
                                                                                                                                         vowels ++;
                                                                                                                                     } else
                                                                                                                                         if ((int )c == 69) {
                                                                                                                                             vowels ++;
                                                                                                                                         } else
                                                                                                                                             if ((int )c == 73) {
                                                                                                                                                 vowels ++;
                                                                                                                                             } else
                                                                                                                                                 if ((int )c == 79) {
                                                                                                                                                     vowels ++;
                                                                                                                                                 } else
                                                                                                                                                     if ((int )c == 85) {
                                                                                                                                                         vowels ++;
                                                                                                                                                     } else {
                                                                                                                                                         consonants ++;
                                                                                                                                                     }
                                                                                                             }
                                                                                                         }
                                                                                                         i ++;
                                                                                             }
                                                                                             printf((char const   */* __restrict  */)"Analysis of \'%s\':\n", str);
                                                                                             printf((char const   */* __restrict  */)"Length: %d\n", length);
                                                                                             printf((char const   */* __restrict  */)"Vowels: %d\n", vowels);
                                                                                             printf((char const   */* __restrict  */)"Consonants: %d\n", consonants);
                                                                                             printf((char const   */* __restrict  */)"Digits: %d\n", digits);
                                                                                             return ((vowels + consonants) + digits);
                                                                                         }
                                                                                     }
                                                                                     int main(int _formal_argc , char **_formal_argv , char **_formal_envp )
                                                                                     {
                                                                                         int i ;
                                                                                         int tmp ;
                                                                                         int scores[5] ;
                                                                                         int i___0 ;
                                                                                         int tmp___0 ;
                                                                                         int test_array[8] ;
                                                                                         int array_size ;
                                                                                         int _BARRIER_0 ;
                                                                                         unsigned long _1_main_next ;

                                                                                         {
                                                                                             megaInit();
                                                                                             _global_argc = _formal_argc;
                                                                                             _global_argv = _formal_argv;
                                                                                             _global_envp = _formal_envp;
                                                                                             _BARRIER_0 = 1;
                                                                                             {
                                                                                                 _1_main_next = 11UL;
                                                                                             }
                                                                                             while (1) {
                                                                                                 switch (_1_main_next) {
                                                                                                     case 8:
                                                                                                         printf((char const   */* __restrict  */)"\n");
                                                                                                         printf((char const   */* __restrict  */)"Array processing:\n");
                                                                                                         test_array[0] = 10;
                                                                                                         test_array[1] = 25;
                                                                                                         test_array[2] = 3;
                                                                                                         test_array[3] = 47;
                                                                                                         test_array[4] = 8;
                                                                                                         test_array[5] = 91;
                                                                                                         test_array[6] = 2;
                                                                                                         test_array[7] = 36;
                                                                                                         array_size = (int )(sizeof(test_array) / sizeof(test_array[0]));
                                                                                                         array_processor(test_array, array_size);
                                                                                                         printf((char const   */* __restrict  */)"\n");
                                                                                                         printf((char const   */* __restrict  */)"String analysis:\n");
                                                                                                         string_analyzer("Hello World 123");
                                                                                                         printf((char const   */* __restrict  */)"\n");
                                                                                                         printf((char const   */* __restrict  */)"Menu simulation:\n");
                                                                                                         menu_handler(1);
                                                                                                         menu_handler(3);
                                                                                                         menu_handler(99);
                                                                                                         printf((char const   */* __restrict  */)"\nProgram completed successfully!\n");
                                                                                                         {
                                                                                                             _1_main_next = 5UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 1:
                                                                                                         printf((char const   */* __restrict  */)"\n\n");
                                                                                                         printf((char const   */* __restrict  */)"Grade calculations:\n");
                                                                                                         scores[0] = 95;
                                                                                                         scores[1] = 87;
                                                                                                         scores[2] = 76;
                                                                                                         scores[3] = 65;
                                                                                                         scores[4] = 45;
                                                                                                         i___0 = 0;
                                                                                                         {
                                                                                                             _1_main_next = 3UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 3: ;
                                                                                                     if (i___0 < 5) {
                                                                                                         {
                                                                                                             _1_main_next = 2UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_main_next = 8UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 11:
                                                                                                         printf((char const   */* __restrict  */)"=== Control Flow Flattening Demo ===\n\n");
                                                                                                         printf((char const   */* __restrict  */)"Fibonacci sequence (first 10 numbers):\n");
                                                                                                         i = 0;
                                                                                                         {
                                                                                                             _1_main_next = 0UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 9:
                                                                                                         tmp = fibonacci(i);
                                                                                                         printf((char const   */* __restrict  */)"%d ", tmp);
                                                                                                         i ++;
                                                                                                         {
                                                                                                             _1_main_next = 0UL;
                                                                                                         }
                                                                                                         break;
                                                                                                     case 5: ;
                                                                                                     return (0);
                                                                                                     break;
                                                                                                     case 0: ;
                                                                                                     if (i < 10) {
                                                                                                         {
                                                                                                             _1_main_next = 9UL;
                                                                                                         }
                                                                                                     } else {
                                                                                                         {
                                                                                                             _1_main_next = 1UL;
                                                                                                         }
                                                                                                     }
                                                                                                     break;
                                                                                                     case 2:
                                                                                                         tmp___0 = grade_calculator(scores[i___0]);
                                                                                                         printf((char const   */* __restrict  */)"Score %d gets grade: %c\n", scores[i___0],
                                                                                                                tmp___0);
                                                                                                         i___0 ++;
                                                                                                         {
                                                                                                             _1_main_next = 3UL;
                                                                                                         }
                                                                                                         break;
                                                                                                 }
                                                                                             }
                                                                                         }
                                                                                     }
